### ISSUE TITLE
Make datastore agnostic

### ISSUE THREAD

**Issue by MattGson** [lolopinto/ent#1210]
Ideally some or all of the data could be stored in a different database.

Object databases and memory caches would be the obvious choices to support. These allows potential big performance gains and horizontal scaling without complex custom sharding.

**Comment by lolopinto** [comment]
unlikely the datastore will ever be agonostic. since a lot of the database layer is intended to be taken care of, can't do that without understanding the underlying datastore/database layer.

having a caching layer that's agonostic is definitely on the cards but haven't needed it yet for anything in production so it hasn't been prioritized. 

My guess is redis, memory and maybe memcache will be the first few supported.
